"""reupdate

Revision ID: 0e677ac00567
Revises: cbaf0992e349
Create Date: 2024-03-25 00:03:30.612460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e677ac00567'
down_revision = 'cbaf0992e349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pizzas_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])

    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('pizzas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('restaurants_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('restaurants_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pizzas_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pizzas_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
