"""populate

Revision ID: 32badea0c9cb
Revises: b48e143f063a
Create Date: 2024-03-24 22:35:15.747102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32badea0c9cb'
down_revision = 'b48e143f063a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_pizza',
    sa.Column('pizzas_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pizzas_id'], ['pizzas.id'], name=op.f('fk_restaurant_pizza_pizzas_id_pizzas')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_pizza_restaurant_id_restaurants'))
    )
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pizzas_restaurants_id_restaurants', type_='foreignkey')
        batch_op.drop_column('restaurants_id')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_restaurants_pizzas_id_pizzas', type_='foreignkey')
        batch_op.drop_column('pizzas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizzas_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_restaurants_pizzas_id_pizzas', 'pizzas', ['pizzas_id'], ['id'])

    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurants_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pizzas_restaurants_id_restaurants', 'restaurants', ['restaurants_id'], ['id'])

    op.drop_table('restaurant_pizza')
    # ### end Alembic commands ###
